# Generated by Django 4.secrets.json.3 on 2023-01-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagne', '0002_remove_studygroup_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='study_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
